import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validationSteps,requiredValidationSteps,verifyEvidenceRun} from './recover-release.mjs';
function fixture(){return {meta:{repository:{full_name:'logtura/logtura'},head_repository:{full_name:'logtura/logtura'},event:'push',status:'completed',head_sha:'a'.repeat(40),head_branch:'v0.3.2',path:'.github/workflows/release.yml@refs/tags/v0.3.2'},jobs:{jobs:[{name:'release',steps:validationSteps.map(name=>({name,conclusion:'success'}))}]}};}
test('only same-repository completed tag runs with all validation gates can supply recovery archives',()=>{const x=fixture();verifyEvidenceRun(x.meta,x.jobs,'a'.repeat(40),'v0.3.2');});
test('foreign, untagged, unrelated or still-running evidence is refused',()=>{for(const mutation of [x=>x.meta.repository.full_name='foreign/repo',x=>x.meta.head_repository.full_name='foreign/repo',x=>x.meta.event='pull_request',x=>x.meta.status='in_progress',x=>x.meta.head_sha='b'.repeat(40),x=>x.meta.head_branch='main',x=>x.meta.path='.github/workflows/test.yml']){const x=fixture();mutation(x);assert.throws(()=>verifyEvidenceRun(x.meta,x.jobs,'a'.repeat(40),'v0.3.2'));}});
test('missing or failed validation steps cannot authorize recovery publication',()=>{for(const step of validationSteps){const x=fixture();x.jobs.jobs[0].steps=x.jobs.jobs[0].steps.filter(s=>s.name!==step);assert.throws(()=>verifyEvidenceRun(x.meta,x.jobs,'a'.repeat(40),'v0.3.2'));const y=fixture();y.jobs.jobs[0].steps.find(s=>s.name===step).conclusion='failure';assert.throws(()=>verifyEvidenceRun(y.meta,y.jobs,'a'.repeat(40),'v0.3.2'));}const x=fixture();assert.throws(()=>verifyEvidenceRun(x.meta,{jobs:[]},'a'.repeat(40),'v0.3.2'));});

test('historical immutable releases retain their original gates without waiving new release transport proof',()=>{const x=fixture();x.meta.head_branch='v0.3.1';x.jobs.jobs[0].steps=requiredValidationSteps('v0.3.1').map(name=>({name,conclusion:'success'}));verifyEvidenceRun(x.meta,x.jobs,'a'.repeat(40),'v0.3.1');for(const tag of ['v0.3.2','v0.4.0','v1.0.0']){x.meta.head_branch=tag;assert.throws(()=>verifyEvidenceRun(x.meta,x.jobs,'a'.repeat(40),tag),/real Supabase/);}assert.throws(()=>requiredValidationSteps('main'));});
