import {test} from 'node:test';
import assert from 'node:assert/strict';
import {assertRegistryMatch,checkTag,integrity,publishOrder,validateManifest,run} from './release-artifacts.mjs';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {normalizePackage} from './normalize-packed.mjs';
const packages=[{name:'@logtura/cli',version:'0.2.12',dependencies:{'@logtura/core':'workspace:*'}},{name:'@logtura/core',version:'0.2.12'}];
test('archive normalization stabilizes dependency order without changing conditional exports',()=>{const exports={'.':{types:'./dist/index.d.ts',development:'./src/index.ts',default:'./dist/index.js'}},a={name:'@logtura/core',exports,dependencies:{z:'1',a:'2'}},b={...a,dependencies:{a:'2',z:'1'}};assert.equal(JSON.stringify(normalizePackage(a)),JSON.stringify(normalizePackage(b)));assert.deepEqual(Object.keys(normalizePackage(a).exports['.']),['types','development','default']);assert.deepEqual(Object.keys(a.dependencies),['z','a']);});
function fixture(){const bytes=Buffer.from('tested archive');return {bytes,manifest:{schemaVersion:1,version:'0.2.12',sourceCommit:'a'.repeat(40),sourceClean:true,packages:packages.map(p=>({name:p.name,version:p.version,file:`${p.name.replace('@','').replace('/','-')}-0.2.12.tgz`,integrity:integrity(bytes)}))}};}
test('release tags fence every package version and reject non-stable tags',()=>{assert.equal(checkTag(packages,'v0.2.12'),'0.2.12');for(const tag of ['v0.2.11','0.2.12','v0.2.12-rc.1',undefined])assert.throws(()=>checkTag(packages,tag));assert.throws(()=>checkTag([{...packages[0],version:'0.2.11'},packages[1]],'v0.2.12'));});
test('release order installs dependencies first and refuses cycles',()=>{assert.deepEqual(publishOrder(packages).map(p=>p.name),['@logtura/core','@logtura/cli']);assert.throws(()=>publishOrder([packages[0],{...packages[1],optionalDependencies:{'@logtura/cli':'workspace:*'}}]));});
test('manifest binds the clean commit and every tested archive before publishing',()=>{const {bytes,manifest}=fixture();assert.deepEqual(validateManifest(manifest,packages,'v0.2.12',()=>bytes).map(p=>p.name),['@logtura/core','@logtura/cli']);assert.throws(()=>validateManifest({...manifest,sourceClean:false},packages,'v0.2.12',()=>bytes));assert.throws(()=>validateManifest({...manifest,sourceCommit:'unknown'},packages,'v0.2.12',()=>bytes));assert.throws(()=>validateManifest(manifest,packages,'v0.2.12',()=>Buffer.from('repacked')));});
test('missing, duplicated, substituted or path-traversing archives cannot be released',()=>{const {bytes,manifest}=fixture();for(const rows of [manifest.packages.slice(1),[manifest.packages[0],manifest.packages[0]],manifest.packages.map((p,i)=>i?{...p,name:'@logtura/foreign'}:p),manifest.packages.map((p,i)=>i?{...p,file:'../core.tgz'}:p)])assert.throws(()=>validateManifest({...manifest,packages:rows},packages,'v0.2.12',()=>bytes));});
test('already published versions are resumable only when exact archive integrity matches',()=>{const {manifest}=fixture(),row=manifest.packages[0];assert.equal(assertRegistryMatch(row,null),false);assert.equal(assertRegistryMatch(row,{name:row.name,version:row.version,dist:{integrity:row.integrity}}),true);for(const value of [{name:row.name,version:row.version,dist:{integrity:integrity(Buffer.from('old source'))}},{name:row.name,version:row.version},{name:'@logtura/foreign',version:row.version,dist:{integrity:row.integrity}}])assert.throws(()=>assertRegistryMatch(row,value));});

function checkout(t){
 const root=mkdtempSync(join(tmpdir(),'logtura-release-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 for(const p of packages){const path=join(root,'packages',p.name.split('/')[1]);mkdirSync(path,{recursive:true});writeFileSync(join(path,'package.json'),JSON.stringify(p));}
 writeFileSync(join(root,'packages/LICENSE'),'fixture license');
 function git(args){const x=spawnSync('git',args,{cwd:root,encoding:'utf8'});assert.equal(x.status,0,x.stderr);return x.stdout.trim();}
 git(['init','-q']);git(['add','packages']);git(['-c','user.name=Release Test','-c','user.email=release@example.test','commit','-qm','fixture']);
 const {bytes,manifest}=fixture();manifest.sourceCommit=git(['rev-parse','HEAD']);const directory=join(root,'.tmp/release');mkdirSync(directory,{recursive:true});
 for(const row of manifest.packages)writeFileSync(join(directory,row.file),bytes);
 const file=join(directory,'manifest.json');writeFileSync(file,JSON.stringify(manifest));
 const state=new Map(),published=[];const options={root,tag:'v0.2.12',fetch:async url=>{assert.ok(url.startsWith('https://registry.npmjs.org/'));const name=decodeURIComponent(url.split('/').at(-2));return state.has(name)?Response.json(state.get(name)):new Response('',{status:404});},publish:async args=>{assert.deepEqual(args.slice(2),['--access','public','--provenance','--registry','https://registry.npmjs.org/']);const row=manifest.packages.find(r=>join(directory,r.file)===args[1]);assert.ok(row);published.push(row.name);state.set(row.name,{name:row.name,version:row.version,dist:{integrity:row.integrity}});}};
 return {file,manifest,state,published,options,receipt:()=>JSON.parse(readFileSync(join(directory,'registry-receipt.json'),'utf8'))};
}
test('CLI release orchestration validates all versions before dependency-ordered publication and recovery',async t=>{const x=checkout(t);await run(['--publish',x.file],x.options);assert.deepEqual(x.published,['@logtura/core','@logtura/cli']);assert.equal(x.receipt().status,'verified');await run(['--publish',x.file],x.options);assert.equal(x.published.length,2);assert.ok(x.receipt().packages.every(p=>p.reused));await run(['--verify',x.file],x.options);});
test('a later inventory collision prevents even an earlier missing package from publishing',async t=>{const x=checkout(t),row=x.manifest.packages[0];x.state.set(row.name,{name:row.name,version:row.version,dist:{integrity:'sha512-foreign'}});await assert.rejects(run(['--publish',x.file],x.options),/differs from the tested archive/);assert.deepEqual(x.published,[]);assert.equal(x.receipt().status,'incomplete');});
test('partial publication retains its receipt and resumes only the missing exact archives',async t=>{const x=checkout(t),publish=x.options.publish;x.options.publish=async args=>{if(args[1].includes('logtura-cli-'))throw new Error('injected publisher failure');await publish(args);};await assert.rejects(run(['--publish',x.file],x.options),/publisher failure/);assert.equal(x.receipt().status,'incomplete');assert.deepEqual(x.receipt().packages.map(p=>p.name),['@logtura/core']);x.options.publish=publish;await run(['--publish',x.file],x.options);assert.deepEqual(x.published,['@logtura/core','@logtura/cli']);assert.equal(x.receipt().status,'verified');});
test('registry failures and missing verification cannot produce a completed release',async t=>{const x=checkout(t);await assert.rejects(run(['--verify',x.file],x.options),/Missing published/);assert.equal(x.receipt().status,'incomplete');x.options.fetch=async()=>new Response('',{status:503});await assert.rejects(run(['--publish',x.file],x.options),/Registry observation failed/);assert.deepEqual(x.published,[]);});
