coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 95%
        threshold: 0%
comment:
  layout: "reach,diff,flags,files"
  behavior: default
component_management:
  individual_components:
    - component_id: public_packages
      name: Public packages
      paths:
        - packages/**
    - component_id: service_backend
      name: Service backend
      paths:
        - src/**
        - "!src/web/**"
    - component_id: service_ui
      name: Service UI
      paths:
        - src/web/**
