import {expect,it,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {validateFlyCleanupRequest,validateFlyCleanupReceipt,validateFlyCleanupRebaseReceipt,type FlyCleanupRequest} from "../src/fly-cleanup";
import {LogturaServiceClient} from "../src/service-client";
const hash=(c:string)=>`sha256:${c.repeat(64)}`;
function fixture(){
 const binding={request:{requestId:randomUUID(),instanceId:randomUUID(),expectedConfigurationVersion:2,expectedSequence:1,revision:hash("a"),appName:"app",orgSlug:"personal",region:"iad",previousMachineId:"abc123",expectedImageDigest:null,previousImageDigest:hash("b"),previousConfigDigest:hash("c"),machineId:"def456",imageDigest:hash("d")},configurationVersion:3};
 const request:FlyCleanupRequest={requestId:randomUUID(),bindingRequestId:binding.request.requestId,rollbackRequestId:null,expectedConfigurationVersion:3,expectedSequence:1,revision:hash("a"),expectedInstanceId:binding.request.instanceId,imageDigest:hash("d"),survivorConfigDigest:hash("e"),retiredConfigDigest:hash("f")};
 const prepared={request,binding,rollback:null,fence:{configurationVersion:3,sequence:1,revision:hash("a")},status:"prepared" as const};
 const rebase={cleanupId:request.requestId,request:{requestId:randomUUID(),...prepared.fence}};
 return {binding,request,prepared,completed:{...prepared,status:"completed" as const},rebase};
}
it("validates strict public reservations without allowing private payloads or inconsistent restoration proofs",()=>{
 const f=fixture();expect(validateFlyCleanupRequest(f.request)).toEqual(f.request);expect(validateFlyCleanupReceipt(f.prepared)).toEqual(f.prepared);expect(validateFlyCleanupReceipt(f.completed)).toEqual(f.completed);
 for(const value of [null,[],{}, {...f.request,extra:"private"},{...f.request,requestId:"bad"},{...f.request,bindingRequestId:"bad"},{...f.request,rollbackRequestId:"bad"},{...f.request,expectedInstanceId:null},{...f.request,expectedConfigurationVersion:-1},{...f.request,expectedConfigurationVersion:NaN},{...f.request,expectedConfigurationVersion:Number.MAX_SAFE_INTEGER},{...f.request,expectedSequence:0},{...f.request,expectedSequence:NaN},{...f.request,revision:"bad"},{...f.request,imageDigest:null},{...f.request,survivorConfigDigest:"bad"},{...f.request,retiredConfigDigest:"bad"},{...f.request,rollbackRequestId:randomUUID()}])expect(()=>validateFlyCleanupRequest(value)).toThrow();
 for(const value of [null,[],{}, {...f.prepared,status:"unknown"},{...f.prepared,extra:true},{...f.prepared,request:{...f.request,bindingRequestId:randomUUID()}},{...f.prepared,request:{...f.request,expectedConfigurationVersion:2}},{...f.prepared,fence:{...f.prepared.fence,configurationVersion:2}},{...f.prepared,fence:{...f.prepared.fence,sequence:0}},{...f.prepared,request:{...f.request,expectedSequence:2}},{...f.prepared,binding:{...f.binding,configurationVersion:2,request:{...f.binding.request,previousMachineId:"def456"}}},{...f.prepared,fence:{...f.prepared.fence,revision:hash("b")}}])expect(()=>validateFlyCleanupReceipt(value)).toThrow();
 const rollbackRequest={requestId:randomUUID(),bindingRequestId:f.binding.request.requestId,expectedConfigurationVersion:3,expectedSequence:1,revision:hash("a"),expectedInstanceId:f.binding.request.instanceId,expectedImageDigest:hash("d"),candidateConfigDigest:hash("e")};
 const rollback={request:rollbackRequest,binding:f.binding,status:"completed" as const,configurationVersion:4,fence:f.prepared.fence};
 const restored={...f.prepared,rollback,request:{...f.request,rollbackRequestId:rollbackRequest.requestId,expectedInstanceId:null,expectedConfigurationVersion:4,imageDigest:hash("b")},fence:{...f.prepared.fence,configurationVersion:4}};
 expect(validateFlyCleanupReceipt(restored)).toEqual(restored);
 for(const value of [{...f.prepared,rollback},{...restored,rollback:null},{...restored,rollback:{...rollback,binding:{...f.binding,request:{...f.binding.request,previousConfigDigest:hash("a")}}}},{...restored,rollback:{...rollback,status:"prepared",configurationVersion:3}},{...restored,request:{...restored.request,rollbackRequestId:randomUUID()}},{...restored,request:{...restored.request,imageDigest:hash("a")}},{...restored,request:{...restored.request,expectedConfigurationVersion:3}},{...restored,rollback:{...rollback,request:{...rollback.request,requestId:randomUUID()}}}])expect(()=>validateFlyCleanupReceipt(value)).toThrow();
 const copy=validateFlyCleanupReceipt(restored);copy.request.expectedSequence=2;expect(restored.request.expectedSequence).toBe(1);
 expect(validateFlyCleanupRebaseReceipt(f.rebase)).toEqual(f.rebase);for(const value of [null,[],{}, {...f.rebase,extra:1},{...f.rebase,cleanupId:"bad"}])expect(()=>validateFlyCleanupRebaseReceipt(value)).toThrow();
});
it("roundtrips owner cleanup/rebase routes with exact acknowledgements and rejects malformed or cross-intent responses",async()=>{
 const f=fixture(),fetcher=vi.fn<typeof fetch>(async(url)=>Response.json(String(url).includes("/rebases")?f.rebase:String(url).endsWith("/complete")?f.completed:f.prepared));
 const client=new LogturaServiceClient({url:"https://service.test",token:`lt_cli_${"x".repeat(43)}`,fetch:fetcher}),id="dep/name";
 expect(await client.prepareFlyCleanup(id,f.request)).toEqual(f.prepared);expect(await client.getFlyCleanup(id,f.request.requestId)).toEqual(f.prepared);expect(await client.completeFlyCleanup(id,f.request.requestId)).toEqual(f.completed);expect(await client.rebaseFlyCleanup(id,f.request.requestId,f.rebase.request)).toEqual(f.rebase);expect(await client.getFlyCleanupRebase(id,f.request.requestId,f.rebase.request.requestId)).toEqual(f.rebase);expect(String(fetcher.mock.calls[0]![0])).toContain("dep%2Fname");
 const operations=[()=>client.prepareFlyCleanup(id,f.request),()=>client.getFlyCleanup(id,f.request.requestId),()=>client.completeFlyCleanup(id,f.request.requestId),()=>client.rebaseFlyCleanup(id,f.request.requestId,f.rebase.request),()=>client.getFlyCleanupRebase(id,f.request.requestId,f.rebase.request.requestId)];
 for(const body of [{},null,{...f.prepared,request:{...f.request,requestId:randomUUID()}},{...f.rebase,cleanupId:randomUUID()},{...f.rebase,request:{...f.rebase.request,requestId:randomUUID()}}]){fetcher.mockImplementation(async()=>Response.json(body));for(const op of operations)await expect(op()).rejects.toThrow();}
 fetcher.mockImplementation(async()=>Response.json(f.prepared));await expect(client.completeFlyCleanup(id,f.request.requestId)).rejects.toMatchObject({code:"invalid_cleanup_receipt"});
 fetcher.mockImplementation(async()=>Response.json({error:"receipt_not_found"},{status:404}));expect(await client.getFlyCleanup(id,f.request.requestId)).toBeNull();expect(await client.getFlyCleanupRebase(id,f.request.requestId,f.rebase.request.requestId)).toBeNull();
 fetcher.mockImplementation(async()=>Response.json({error:"not_found"},{status:404}));await expect(client.getFlyCleanup(id,f.request.requestId)).rejects.toMatchObject({status:404});await expect(client.getFlyCleanupRebase(id,f.request.requestId,f.rebase.request.requestId)).rejects.toMatchObject({status:404});
 fetcher.mockImplementation(async()=>{throw new Error("network lost");});await expect(client.getFlyCleanup(id,f.request.requestId)).rejects.toThrow("network lost");await expect(client.getFlyCleanupRebase(id,f.request.requestId,f.rebase.request.requestId)).rejects.toThrow("network lost");
 for(const op of [()=>client.prepareFlyCleanup("",f.request),()=>client.getFlyCleanup("",f.request.requestId),()=>client.getFlyCleanup(id,"bad"),()=>client.completeFlyCleanup("",f.request.requestId),()=>client.completeFlyCleanup(id,"bad"),()=>client.rebaseFlyCleanup("",f.request.requestId,f.rebase.request),()=>client.rebaseFlyCleanup(id,"bad",f.rebase.request),()=>client.getFlyCleanupRebase("",f.request.requestId,f.rebase.request.requestId),()=>client.getFlyCleanupRebase(id,"bad",f.rebase.request.requestId),()=>client.getFlyCleanupRebase(id,f.request.requestId,"bad")])await expect(op()).rejects.toThrow();
});
