import type { BundleEnvVar, GeneratedBundle } from "./types";
import { shellQuote } from "./install";
import { runtimeAssetFiles } from "./runtime-assets";
import type { TarFile } from "./tar";

/** Shared Fly self-deploy settings for the hosted download and standalone CLI. */
export function renderFlyToml(input: {
  appName: string;
  region: string;
  envVars?: string[];
}): string {
  validateTarget(input);
  const lines: string[] = [];
  lines.push("# Generated by logtura — https://logtura.dev");
  lines.push(`app = "${input.appName}"`);
  lines.push(`primary_region = "${input.region}"`);
  lines.push("");
  lines.push("[build]");
  lines.push('  dockerfile = "Dockerfile"');
  lines.push("");
  lines.push("# Vector forwarder is always-on; one Machine, no autostop.");
  lines.push("[[vm]]");
  lines.push('  cpu_kind = "shared"');
  lines.push("  cpus = 1");
  lines.push("  memory_mb = 512");
  lines.push("");
  // Heartbeat exporter port; not exposed publicly. Fly's internal
  // network can scrape it from another app.
  lines.push("[[services]]");
  lines.push("  internal_port = 9598");
  lines.push('  protocol = "tcp"');
  lines.push("  auto_stop_machines = false");
  lines.push("  auto_start_machines = true");
  lines.push("  min_machines_running = 1");
  lines.push("");
  if (input.envVars !== undefined) {
    lines.push("# Required env-var secrets (set via `flyctl secrets set`):");
    for (const name of input.envVars) lines.push(`#   ${name}`);
  }
  return lines.join("\n");
}

function validateTarget(input: {appName: string; region: string; envVars?: string[]}): void {
  if (typeof input.appName !== "string" || !/^[a-z0-9][a-z0-9-]{0,62}$/.test(input.appName)) throw new Error("Invalid Fly app name");
  if (typeof input.region !== "string" || !/^[a-z]{3}$/.test(input.region)) throw new Error("Invalid Fly region");
  for (const name of input.envVars ?? []) if (typeof name !== "string" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) throw new Error("Invalid Fly environment name");
}

/** Private self-deploy script: known values remain literal argv data; missing
 * values must be supplied by the caller before any provider operation begins. */
export function renderFlyLaunchScript(input: {appName: string; region?: string; envVars: Pick<BundleEnvVar, "name" | "value">[]}): string {
  validateTarget({appName: input.appName, region: input.region === undefined ? "iad" : input.region, envVars: input.envVars.map(v => v.name)});
  for (const variable of input.envVars) {
    if (variable.value !== null && (typeof variable.value !== "string" || variable.value.includes("\0"))) throw new Error("Invalid Fly environment value");
  }
  const missing = input.envVars.filter(v => v.value === null || v.value === "");
  const args = input.envVars.map(v => v.value === null || v.value === ""
    ? `"${v.name}=\${${v.name}}"` : shellQuote(`${v.name}=${v.value}`));
  return [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# This private script contains generated credentials. Do not share it.",
    ...missing.map(v => `: "\${${v.name}:?Set ${v.name} before running deploy.sh}"`),
    "",
    "# Step 1: create the Fly app (no first deploy yet).",
    `flyctl launch --copy-config --no-deploy --name ${input.appName}${input.region === undefined ? "" : ` --region ${input.region}`}`,
    "",
    ...(args.length ? ["# Step 2: set the secrets the running container needs.",
      `flyctl secrets set --app ${input.appName} \\\n  ${args.join(" \\\n  ")}`, ""] : []),
    "# Step 3: deploy.",
    `flyctl deploy --app ${input.appName}`,
    "",
  ].join("\n");
}

/** Complete self-deploy build context, preserving runtime asset bytes and modes. */
export function flySelfDeployFiles(input: {bundle: GeneratedBundle; appName: string; region?: string}): TarFile[] {
  const assets = runtimeAssetFiles(input.bundle.runtimeAssets);
  return [
    {name: "Dockerfile", content: input.bundle.dockerfile},
    {name: "vector.yaml", content: input.bundle.vectorYaml},
    {name: "fly.toml", content: renderFlyToml({appName: input.appName, region: input.region ?? "iad", envVars: input.bundle.envVars.map(v => v.name)})},
    {name: "deploy.sh", content: renderFlyLaunchScript({appName: input.appName, region: input.region, envVars: input.bundle.envVars}), mode: 0o600},
    ...assets.map(file => ({...file, mode: file.mode ?? 0o644})),
  ];
}
