/** Shared Fly self-deploy settings for the hosted download and standalone CLI. */
export function renderFlyToml(input: {
  appName: string;
  region: string;
  envVars?: string[];
}): string {
  if (typeof input.appName !== "string" || !/^[a-z0-9][a-z0-9-]{0,62}$/.test(input.appName)) throw new Error("Invalid Fly app name");
  if (typeof input.region !== "string" || !/^[a-z]{3}$/.test(input.region)) throw new Error("Invalid Fly region");
  for (const name of input.envVars ?? []) if (typeof name !== "string" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) throw new Error("Invalid Fly environment name");
  const lines: string[] = [];
  lines.push("# Generated by logtura — https://logtura.dev");
  lines.push(`app = "${input.appName}"`);
  lines.push(`primary_region = "${input.region}"`);
  lines.push("");
  lines.push("[build]");
  lines.push('  dockerfile = "Dockerfile"');
  lines.push("");
  lines.push("# Vector forwarder is always-on; one Machine, no autostop.");
  lines.push("[[vm]]");
  lines.push('  cpu_kind = "shared"');
  lines.push("  cpus = 1");
  lines.push("  memory_mb = 512");
  lines.push("");
  // Heartbeat exporter port; not exposed publicly. Fly's internal
  // network can scrape it from another app.
  lines.push("[[services]]");
  lines.push("  internal_port = 9598");
  lines.push('  protocol = "tcp"');
  lines.push("  auto_stop_machines = false");
  lines.push("  auto_start_machines = true");
  lines.push("  min_machines_running = 1");
  lines.push("");
  if (input.envVars !== undefined) {
    lines.push("# Required env-var secrets (set via `flyctl secrets set`):");
    for (const name of input.envVars) lines.push(`#   ${name}`);
  }
  return lines.join("\n");
}
