import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,chmodSync,rmSync,symlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {smokeProduction,PRODUCTION_ORIGIN,PRODUCTION_DEPLOYMENT} from '../../scripts/smoke-production.mjs';
const now=1800000000000,token=`lt_cli_${'a'.repeat(43)}`;
function fixture(){const directory=mkdtempSync(join(tmpdir(),'logt-smoke-'));chmodSync(directory,0o700);const authFile=join(directory,'account.json');const credential={token,scope:'account:read account:write',expiresAt:253402300799999,service:PRODUCTION_ORIGIN};const write=value=>writeFileSync(authFile,JSON.stringify(value),{mode:0o600});write(credential);return {directory,authFile,credential,write};}
const responses=()=>[{user:{id:'fixture',githubLogin:'fixture'}},{deployment:{id:PRODUCTION_DEPLOYMENT,status:'running',lastSeenAt:now-1000}},{state:{desired:{sequence:2,revision:'revision'},applied:{sequence:2,revision:'revision'},lastReportSequence:1,stale:false}}];
test('production smoke only sends GET to the bound production origin and returns no private payloads',async()=>{const f=fixture();try{const data=responses(),paths=[];const result=await smokeProduction({authFile:f.authFile,now,fetch:async(url,init)=>{paths.push(url);assert.equal(new URL(url).origin,PRODUCTION_ORIGIN);assert.equal(init.method,'GET');assert.equal(init.redirect,'manual');assert.equal(init.credentials,'omit');assert.equal(init.headers.authorization,`Bearer ${token}`);return Response.json(data.shift());}});assert.equal(paths.length,3);assert.equal(result.configurationCurrent,true);assert.equal(result.heartbeatAgeSeconds,1);assert.ok(!JSON.stringify(result).includes(token));}finally{rmSync(f.directory,{recursive:true,force:true});}});
test('rejects unsafe, expired, foreign or malformed credentials before contacting production',async()=>{const f=fixture();try{const fetch=()=>{throw Error('must not contact service');};for(const mutation of [{service:'https://foreign.test'},{token:'bad'},{expiresAt:now},{expiresAt:Infinity},{scope:'reporting'}]){f.write({...f.credential,...mutation});await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch}),/credential/);}f.write(f.credential);chmodSync(f.authFile,0o644);await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch}),/credential/);chmodSync(f.authFile,0o600);chmodSync(f.directory,0o755);await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch}),/credential/);chmodSync(f.directory,0o700);const linked=join(f.directory,'link.json');symlinkSync(f.authFile,linked);await assert.rejects(smokeProduction({authFile:linked,now,fetch}),/credential/);writeFileSync(f.authFile,'{');await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch}),/credential/);}finally{rmSync(f.directory,{recursive:true,force:true});}});
test('fails on redirects and provider failures without including response bodies or credentials',async()=>{const f=fixture();try{for(const fetch of [async()=>new Response(token,{status:302,headers:{location:'https://foreign.test'}}),async()=>new Response(token,{status:401}),async()=>{throw Error(token);},async()=>new Response(token,{status:200})]){await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch}),error=>!error.message.includes(token));}}finally{rmSync(f.directory,{recursive:true,force:true});}});
test('rejects stale/wrong deployments and distinguishes waiting configuration from runtime acceptance',async()=>{const f=fixture();try{for(const deployment of [{id:'wrong',status:'running',lastSeenAt:now},{id:PRODUCTION_DEPLOYMENT,status:'stopped',lastSeenAt:now},{id:PRODUCTION_DEPLOYMENT,status:'running',lastSeenAt:now-600001}]){const data=responses();data[1]={deployment};await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch:async()=>Response.json(data.shift())}),/forwarder/);}for(const state of [null,{desired:{sequence:2,revision:'revision'},applied:null,lastReportSequence:0,stale:false}]){const data=responses();data[2]={state};const result=await smokeProduction({authFile:f.authFile,now,fetch:async()=>Response.json(data.shift())});assert.equal(result.configurationCurrent,false);}for(const [index,value] of [[0,{user:null}],[2,{state:{}}]]){const data=responses();data[index]=value;await assert.rejects(smokeProduction({authFile:f.authFile,now,fetch:async()=>Response.json(data.shift())}));}}finally{rmSync(f.directory,{recursive:true,force:true});}});
