import { mkdtempSync,readFileSync,writeFileSync,rmSync,statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { stringify } from "yaml";
import { afterEach,describe,it,expect,vi } from "vitest";
import { createSecretVersioner,exportDeploymentManifest,hashConfigDocument,generateBundle } from "@logtura/core";
import { writePulledConfig } from "../src/pull";
import { applyGraphEditFile,diffGraphFiles,diffRemoteGraph,editGraphFile,exportGraphFile,selectGraphSource } from "../src/graph";
import { loadConfigFile,readConfigDoc } from "../src/config";
import { main } from "../src/main";
const dirs:string[]=[];function dir(){const path=mkdtempSync(join(tmpdir(),"logtura-graph-"));dirs.push(path);return path;}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();for(const path of dirs.splice(0))rmSync(path,{recursive:true,force:true});});
async function setup(){const root=dir(),path=join(root,"logt.yaml");const result=await exportDeploymentManifest({providers:[],destinations:[],connections:[{connection:{id:"con_site",provider:"cloudflare-worker-tail",displayName:"Sites",externalAccountId:"account"},credentials:{apiToken:"private-token"},selectedSources:[{id:"src_site",externalId:"original-site",displayName:"Original",sourceKind:"cf_worker",metadata:{private:"metadata-secret"}}]}],monitors:[]},await createSecretVersioner("private"));await writePulledConfig({...result,revision:await hashConfigDocument(result.document),deployment:{id:"dep_site",displayName:"Sites"}},path);return {root,path,result};}
describe("local portable graph commands",()=>{
  it("selects a new site and preserves all original component identities and versions",async()=>{
    const {path,result,root}=await setup();const first=await selectGraphSource(path,"con_site","new-site");const doc=readConfigDoc(path) as any;expect(doc.connections[0].selectedSources).toHaveLength(2);expect(doc.connections[0].selectedSources[0]).toEqual(result.document.connections[0]!.selectedSources[0]);expect(doc.connections[0].credentials).toEqual(result.document.connections[0]!.credentials);
    const id=doc.connections[0].selectedSources[1].id;expect(id).toMatch(/^src_[a-f0-9]{32}$/);expect(await selectGraphSource(path,"con_site","new-site")).toBe(first);expect(readConfigDoc(path)).toEqual(doc);
    const file=join(root,"metadata.json");writeFileSync(file,JSON.stringify({private:"new-metadata"}));await selectGraphSource(path,"con_site","new-site",{name:"New name",metadataFile:file,id});const parsed=loadConfigFile(path);expect(parsed.input.connections[0]!.selectedSources[1]).toMatchObject({id,displayName:"New name",metadata:{private:"new-metadata"}});expect(readFileSync(path,"utf8")).not.toContain("new-metadata");expect(statSync(join(root,".env")).mode&0o777).toBe(0o600);const bundle=generateBundle(parsed.input);expect(bundle.selectedCount).toBe(2);expect(bundle.vectorYaml).toContain("new-site");expect(bundle.componentManifest.some(c=>c.links?.sourceId==="src_site")).toBe(true);
    writeFileSync(file,"null");await selectGraphSource(path,"con_site","new-site",{metadataFile:file});expect(loadConfigFile(path).input.connections[0]!.selectedSources[1]!.metadata).toBeNull();
    for(const invalid of ["12","[]","false"]){writeFileSync(file,invalid);await expect(selectGraphSource(path,"con_site","new-site",{metadataFile:file})).rejects.toThrow("metadata");}
    const copy=readFileSync(path,"utf8");await expect(selectGraphSource(path,"con_site","new-site",{id:"replacement"})).rejects.toThrow("identity");expect(readFileSync(path,"utf8")).toBe(copy);
  });
  it("requires explicit kinds for empty or mixed inventories and supports explicit source IDs",async()=>{
    const {path}=await setup();await editGraphFile(path,[{kind:"source.remove",id:"src_site"}]);await expect(selectGraphSource(path,"con_site","new-site")).rejects.toThrow("ambiguous");await selectGraphSource(path,"con_site","new-site",{kind:"cf_worker",id:"src_explicit",name:"Explicit"});expect(loadConfigFile(path).input.connections[0]!.selectedSources[0]!.id).toBe("src_explicit");
    await selectGraphSource(path,"con_site","other-kind",{kind:"cf_gateway"});await expect(selectGraphSource(path,"con_site","third-site")).rejects.toThrow("ambiguous");await expect(selectGraphSource(path,"missing","site")).rejects.toThrow("Connection");
  });
  it("applies multi-operation files atomically and describes only changed field names",async()=>{
    const {root,path,result}=await setup(),baseline=join(root,"baseline.yaml"),edits=join(root,"edits.json");writeFileSync(baseline,stringify(result.document));writeFileSync(edits,JSON.stringify([{kind:"source.update",id:"src_site",patch:{displayName:"renamed-secret-label",metadata:{private:"updated-secret"}}},{kind:"connection.update",id:"con_site",patch:{},credentials:{apiToken:"updated-secret-token"}}]));const revision=await applyGraphEditFile(path,edits);const diff=await diffGraphFiles(path,baseline);expect(diff.afterRevision).toBe(revision);expect(diff.changes.map(c=>c.entity)).toEqual(["connection","source"]);expect(JSON.stringify(diff)).not.toContain("updated-secret");expect(JSON.stringify(diff)).not.toContain("renamed-secret-label");
    const before=readFileSync(path,"utf8"),env=readFileSync(join(root,".env"),"utf8");writeFileSync(edits,JSON.stringify([{kind:"source.update",id:"src_site",patch:{displayName:"invalid"}},{kind:"source.remove",id:"missing"}]));await expect(applyGraphEditFile(path,edits)).rejects.toThrow("not found");expect(readFileSync(path,"utf8")).toBe(before);expect(readFileSync(join(root,".env"),"utf8")).toBe(env);
    writeFileSync(edits,'{"apiToken":"unclosed-secret');await expect(applyGraphEditFile(path,edits)).rejects.toThrow("Invalid JSON input file");writeFileSync(edits,'{}');await expect(applyGraphEditFile(path,edits)).rejects.toThrow("array");writeFileSync(edits,'{"private":"unclosed-secret');await expect(selectGraphSource(path,"con_site","site",{metadataFile:edits})).rejects.toThrow("Invalid JSON input file");
  });
  it("exports a shorthand configuration with equivalent standalone rendering inputs",async()=>{
    const root=dir(),path=join(root,"logt.yaml"),output=join(root,"portable.yaml");writeFileSync(path,stringify({providers:{cf:{provider:"cloudflare",account_id:"account",credentials:{api_token:"env:CF_TOKEN"}}},sources:{workers:{source:"cloudflare-worker-tail",scripts:["site"]}},sinks:{},monitors:[]}));writeFileSync(join(root,".env"),"CF_TOKEN=private-token\nUNRELATED=keep\n");
    const expected=loadConfigFile(path).input;const revision=await exportGraphFile(path,output);expect(loadConfigFile(output).input).toEqual(expected);expect(readConfigDoc(output).kind).toBe("logtura.deployment");expect(readFileSync(output,"utf8")).not.toContain("private-token");expect(readFileSync(join(root,".env"),"utf8")).toContain("UNRELATED=keep");expect(await hashConfigDocument(readConfigDoc(output))).toBe(revision);
    const again=join(root,"again.yaml");expect(await exportGraphFile(output,again)).toBe(revision);await expect(exportGraphFile(path,output)).rejects.toThrow("exists");await exportGraphFile(path,output,true);
    await expect(editGraphFile(path,[])).rejects.toThrow("portable");const doc=readConfigDoc(path);(doc.sources as any).workers.scripts=["other"];writeFileSync(path,stringify(doc));rmSync(join(root,".env"));await expect(exportGraphFile(path,join(root,"missing.yaml"))).rejects.toThrow("environment");
  });
  it("compares against the remote current graph without requesting secret payloads",async()=>{
    const {root,path,result}=await setup();vi.stubEnv("LOGT_AUTH_FILE",join(root,"account.json"));vi.stubEnv("LOGT_SERVICE_TOKEN",`lt_cli_${"T".repeat(43)}`);vi.stubEnv("LOGT_SERVICE_URL","https://service.test");vi.stubGlobal("fetch",vi.fn(async(url)=>{expect(url).toBe("https://service.test/api/deployments/dep_site/config");return Response.json({document:result.document,revision:await hashConfigDocument(result.document),deployment:{id:"dep_site",displayName:"Sites"}});}));expect((await diffRemoteGraph(path,"dep_site")).changes).toEqual([]);await selectGraphSource(path,"con_site","new-site");expect((await diffRemoteGraph(path,"dep_site","https://service.test")).changes.some(c=>c.operation==="add")).toBe(true);
  });
  it("executes export, edit, select, remove and local/remote diff through the CLI",async()=>{
    const {root,path,result}=await setup(),edits=join(root,"edits.json"),baseline=join(root,"baseline.yaml");writeFileSync(edits,'[{"kind":"source.update","id":"src_site","patch":{"displayName":"Renamed"}}]');writeFileSync(baseline,stringify(result.document));const log=vi.spyOn(console,"log").mockImplementation(()=>{}),error=vi.spyOn(console,"error").mockImplementation(()=>{});
    const run=(args:string[])=>main(["-c",path,...args]);expect(await run(["config","edit",edits])).toBe(0);expect(await run(["config","diff",baseline])).toBe(0);expect(await run(["config","export","-o",join(root,"copy.yaml"),"--json"])).toBe(0);expect(await run(["config","export","-o",join(root,"copy.yaml"),"--force"])).toBe(0);
    expect(await run(["source","select","con_site","cli-site","--kind","cf_worker","--id","src_cli","--name","CLI","--json"])).toBe(0);expect(await run(["source","remove","src_cli"])).toBe(0);writeFileSync(join(root,"metadata.json"),JSON.stringify({private:"CLI metadata"}));expect(await run(["source","select","con_site","cli-site","--id","src_cli","--metadata-file",join(root,"metadata.json")])).toBe(0);expect(await run(["source","remove","src_cli","--json"])).toBe(0);
    vi.stubEnv("LOGT_AUTH_FILE",join(root,"account.json"));vi.stubEnv("LOGT_SERVICE_TOKEN",`lt_cli_${"T".repeat(43)}`);vi.stubGlobal("fetch",vi.fn(async()=>Response.json({document:result.document,revision:await hashConfigDocument(result.document),deployment:{id:"dep_site",displayName:"Sites"}})));
    expect(await run(["diff","dep_site","--service","https://service.test","--json"])).toBe(0);expect(await run(["diff","dep_site","--service","https://service.test"])).toBe(0);expect(log.mock.calls.some(call=>String(call[0]).includes("update source"))).toBe(true);writeFileSync(path,stringify(result.document));expect(await run(["diff","dep_site","--service","https://service.test"])).toBe(0);expect(log).toHaveBeenCalledWith("No configuration changes");
    for(const args of [["config","edit"],["config","diff",baseline,"extra"],["config","export","--local"],["source","select"],["source","select","-bad","site"],["source","select","con_site","-bad"],["source","select","con_site","site","--local"],["source","remove"],["diff"],["diff","-bad"],["diff","dep_site","--local"]])expect(await run(args)).toBe(1);expect(error).toHaveBeenCalled();
  });
});

it("keeps discovery intent through CLI edits and freezes source discovery on explicit removal",async()=>{
  const {root,path}=await setup(),edits=join(root,"policy.json");writeFileSync(edits,JSON.stringify([{kind:"connection.update",id:"con_site",patch:{},discoverSources:true},{kind:"selection.update",discoverMonitors:true}]));
  vi.spyOn(console,"log").mockImplementation(()=>{});expect(await main(["-c",path,"config","edit",edits])).toBe(0);
  expect(await main(["-c",path,"source","select","con_site","new-site","--id","src_new"])).toBe(0);expect((readConfigDoc(path) as any).connections[0].discoverSources).toBe(true);expect(readConfigDoc(path).discoverMonitors).toBe(true);
  expect(await main(["-c",path,"source","remove","src_new"])).toBe(0);expect((readConfigDoc(path) as any).connections[0].discoverSources).toBe(false);expect(readConfigDoc(path).discoverMonitors).toBe(true);
});
