import { defineConfig } from "vitest/config";

/**
 * Root vitest config for the public @logtura/* monorepo. Fans into
 * every package's own vitest config via `test.projects`.
 */
export default defineConfig({
  test: {
    projects: [
      "./packages/core",
      "./packages/cli",
      "./packages/custom-vector",
      "./packages/cloudflare-shared",
      "./packages/supabase-shared",
      "./packages/destination-datadog-metrics",
      "./packages/destination-prometheus-remote-write",
      "./packages/destination-slack",
      "./packages/destination-webhook",
      "./packages/driver-cloudflare-ai-gateway",
      "./packages/driver-cloudflare-worker-tail",
      "./packages/driver-fly-log-tail",
      "./packages/driver-railway-logs",
      "./packages/driver-supabase-edge-logs",
      "./packages/driver-vercel-logs",
    ],
    coverage: {
      provider: "istanbul",
      reporter: ["text", "html", "lcov", "json-summary"],
      // Final aggregate package target met; all production package source stays included.
      thresholds: {
        "packages/cli/src/**/*.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/custom-vector/src/**/*.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/driver-vercel-logs/src/**/*.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        // Separate package gates keep aggregate coverage from hiding weak drivers.
        "packages/core/src/**/*.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/driver-supabase-edge-logs/src/**/*.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/driver-fly-log-tail/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/driver-cloudflare-ai-gateway/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/driver-cloudflare-worker-tail/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/destination-prometheus-remote-write/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/destination-datadog-metrics/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/destination-slack/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/destination-webhook/src/**/*.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },

        "packages/core/src/docker-install.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/runtime-assets.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/fly-install.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/oci-image.ts": { statements: 100, branches: 98, functions: 100, lines: 100 },
        statements: 95, branches: 92, functions: 96.5, lines: 95.5,
        "packages/core/src/reconcile.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/graph.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/provider-connectors.ts": { statements: 100, branches: 97, functions: 100, lines: 100 },
        "packages/cli/src/local-env.ts": { statements: 98, branches: 94, functions: 100, lines: 100 },
        "packages/cli/src/graph.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/manifest.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/json.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/pull.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/file-transaction.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/deployment-target.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/fly-target.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/deployment-link.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/activation.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/push.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/runtime-process.ts": { statements: 98, branches: 92, functions: 100, lines: 100 },
        "packages/cli/src/runtime-main.ts": { statements: 100, branches: 92, functions: 100, lines: 100 },
        "packages/cli/src/runtime-report.ts": { statements: 97, branches: 95, functions: 100, lines: 100 },
        "packages/cli/src/private-lock.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/push-lock.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/metrics.ts": { statements: 99, branches: 95, functions: 100, lines: 100 },
        "packages/cli/src/metrics.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/fly.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/fly-replacement.ts": { statements: 95, branches: 95, functions: 100, lines: 100 },
        "packages/core/src/fly-runtime.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/fly-apply.ts": { statements: 96, branches: 91, functions: 100, lines: 100 },
        "packages/core/src/runtime-image.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/runtime.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/deployment-state.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/deployment-reporting.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/core/src/service-client.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/cli/src/account.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/core/src/config.ts": { statements: 95, branches: 90, functions: 95, lines: 95 },
        "packages/core/src/install.ts": { statements: 100, branches: 95, functions: 100, lines: 100 },
        "packages/core/src/tar.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/driver-railway-logs/src/index.ts": { statements: 100, branches: 99, functions: 100, lines: 100 },
        "packages/cloudflare-shared/src/**": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "packages/supabase-shared/src/**": { statements: 100, branches: 100, functions: 100, lines: 100 },
      },
      include: ["packages/*/src/**/*.ts"],
      exclude: ["**/*.d.ts"],
    },
  },
});
