import { gzipSync } from "node:zlib";
import type { BundleEnvVar, GeneratedBundle } from "@logtura/core";
import { buildTar, type TarFile } from "./tar";

export function installBundleFiles(
  bundle: GeneratedBundle,
  name = "logtura-forwarder",
): TarFile[] {
  const dirName = name.replace(/[^a-z0-9-]/gi, "-").toLowerCase() || "logtura";
  return [
    { name: `${dirName}/Dockerfile`, content: bundle.dockerfile },
    { name: `${dirName}/vector.yaml`, content: bundle.vectorYaml },
    ...bundle.runtimeAssets.map((asset) => ({
      name: `${dirName}/assets/${asset.driverId}/${asset.path}`,
      content: asset.content,
      mode: asset.mode,
    })),
    { name: `${dirName}/manifest.json`, content: JSON.stringify(bundle.componentManifest, null, 2) },
    { name: `${dirName}/.env`, content: renderEnvFile(bundle.envVars), mode: 0o600 },
    { name: `${dirName}/install.sh`, content: renderInstallSh(dirName, bundle.envVars), mode: 0o755 },
    { name: `${dirName}/README.md`, content: renderReadme(name, bundle.envVars) },
  ];
}

export function buildInstallArchive(
  bundle: GeneratedBundle,
  name = "logtura-forwarder",
): Uint8Array {
  return gzipSync(buildTar(installBundleFiles(bundle, name)));
}

export function renderEnvFile(envVars: BundleEnvVar[]): string {
  const lines = [
    "# Logtura forwarder - generated config",
    "# Do not check this file into git.",
    "",
  ];
  for (const v of envVars) {
    if (v.description) {
      for (const line of v.description.split("\n")) lines.push(`# ${line}`);
    }
    lines.push(v.value ? `${v.name}=${shellQuote(v.value)}` : `# ${v.name}=`);
    lines.push("");
  }
  return lines.join("\n");
}

function renderReadme(displayName: string, envVars: BundleEnvVar[]): string {
  const missing = envVars
    .filter((v) => !v.value)
    .map((v) => `- \`${v.name}\``)
    .join("\n");
  return `# ${displayName}

Generated by \`logtura install-zip\`.

\`\`\`sh
./install.sh
\`\`\`

${missing ? `## Missing env values\n\n${missing}\n` : ""}
`;
}

function renderInstallSh(dirName: string, envVars: BundleEnvVar[]): string {
  const required = envVars.filter((v) => !v.value).map((v) => v.name);
  return `#!/bin/sh
set -eu

IMAGE_TAG="logtura-${dirName}:latest"
CONTAINER_NAME="logtura-forwarder"

if command -v docker >/dev/null 2>&1; then
  RUNTIME=docker
elif command -v podman >/dev/null 2>&1; then
  RUNTIME=podman
else
  echo "docker or podman is required" >&2
  exit 1
fi

if [ -f .env ]; then
  set -a
  . ./.env
  set +a
fi

for key in ${required.join(" ")}; do
  eval "val=\\\${$key:-}"
  if [ -z "$val" ]; then
    echo "missing required env var: $key" >&2
    exit 1
  fi
done

$RUNTIME build -t "$IMAGE_TAG" .
$RUNTIME rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
$RUNTIME run -d --name "$CONTAINER_NAME" --restart=always --env-file .env "$IMAGE_TAG"
echo "running. Tail with: $RUNTIME logs -f $CONTAINER_NAME"
`;
}

function shellQuote(v: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(v)) return v;
  return `'${v.replace(/'/g, `'\\''`)}'`;
}
