import type {
  ConnectionRow,
  DestinationRow,
  LogSourceRow,
  MonitorRow,
  SinkRow,
} from "./db";
import {
  type DestinationDriver,
  getDestinationDriver,
} from "./destinations";
import { getProvider } from "./providers";
import type {
  ConnectionRef,
  DockerfileDep,
  EnvVarSpec,
  ProviderDriver,
  SourceRef,
} from "./providers";

export interface BundleEnvVar {
  name: string;
  description: string;
  source: "credential" | "external_account_id" | "destination" | "manual";
  /** When non-null, the bundle UI shows this real value (the user
   *  already provided it via destinations / connections). When null,
   *  the user has to fill the value themselves at docker-run time. */
  value: string | null;
}

export interface GeneratedBundle {
  vectorYaml: string;
  dockerfile: string;
  runCommand: string;
  envVars: BundleEnvVar[];
  selectedCount: number;
  /** A best-effort summary like "2 monitors → 3 sinks" for the UI. */
  monitorSummary: string;
}

export interface GeneratorMonitor {
  monitor: MonitorRow;
  sinks: GeneratorSink[];
}

export interface GeneratorSink {
  sink: SinkRow;
  destination: DestinationRow;
  /** Pre-decrypted destination config — caller decrypts (so the
   *  generator stays sync and doesn't depend on env). */
  destinationConfig: unknown;
}

interface GenerateInput {
  connection: ConnectionRow;
  selectedSources: LogSourceRow[];
  monitors: GeneratorMonitor[];
}

export function generateBundle(input: GenerateInput): GeneratedBundle {
  const driver = getProvider(input.connection.provider);
  if (!driver) {
    throw new Error(`Unknown provider: ${input.connection.provider}`);
  }
  const connectionRef: ConnectionRef = {
    id: input.connection.id,
    externalAccountId: input.connection.external_account_id,
    displayName: input.connection.display_name,
  };
  const sourceRefs: SourceRef[] = input.selectedSources.map((s) => ({
    externalId: s.external_id,
    displayName: s.display_name,
    sourceKind: s.source_kind,
    metadata: s.metadata_json ? JSON.parse(s.metadata_json) : null,
  }));

  const sourceSpec = driver.runtimeSpec(connectionRef);

  const { vectorYaml, sinkEnvVars } = renderVectorYaml(
    connectionRef,
    driver,
    sourceRefs,
    input.monitors,
  );

  const dockerfile = renderDockerfile([sourceSpec.dockerfileDeps].flat());

  const envVars: BundleEnvVar[] = [
    ...sourceSpec.envVars.map((e) => ({
      name: e.name,
      description: e.description,
      source: e.source,
      // Source-side env vars (CF token, account id) we don't have
      // here; user supplies at docker-run time. external_account_id
      // we do have on the connection — fill it.
      value:
        e.source === "external_account_id"
          ? (input.connection.external_account_id ?? null)
          : null,
    })),
    ...sinkEnvVars,
  ];

  const runCommand = renderRunCommand(envVars);
  const sinkCount = input.monitors.reduce(
    (n, m) => n + m.sinks.length,
    0,
  );

  return {
    vectorYaml,
    dockerfile,
    runCommand,
    envVars,
    selectedCount: sourceRefs.length,
    monitorSummary:
      input.monitors.length === 0
        ? "no monitors yet"
        : `${input.monitors.length} monitor${input.monitors.length === 1 ? "" : "s"} → ${sinkCount} sink${sinkCount === 1 ? "" : "s"}`,
  };
}

function renderVectorYaml(
  connection: ConnectionRef,
  driver: ProviderDriver,
  sources: SourceRef[],
  monitors: GeneratorMonitor[],
): { vectorYaml: string; sinkEnvVars: BundleEnvVar[] } {
  const lines: string[] = [];
  const sinkEnvVars: BundleEnvVar[] = [];

  lines.push("# Generated by logtura — https://logtura.dev");
  lines.push(`# Connection: ${connection.displayName}`);
  lines.push(`# Provider: ${driver.id}`);
  lines.push(`# Account: ${connection.externalAccountId ?? "unknown"}`);
  lines.push("");
  lines.push("api:");
  lines.push("  enabled: true");
  lines.push('  address: "0.0.0.0:8686"');
  lines.push("");

  // ---- sources -----------------------------------------------------
  lines.push("sources:");
  const sourceKeys: string[] = [];
  if (sources.length === 0) {
    lines.push(
      "  # No sources selected — pipeline runs with heartbeat only.",
    );
  } else {
    for (const s of sources) {
      const block = driver.generateSourceBlock({ source: s, connection });
      lines.push(`  ${block.key}:`);
      lines.push(block.yaml);
      sourceKeys.push(block.key);
    }
  }
  lines.push("  internal_metrics:");
  lines.push("    type: internal_metrics");
  lines.push("    scrape_interval_secs: 30");
  lines.push("");

  // ---- transforms --------------------------------------------------
  lines.push("transforms:");
  if (sourceKeys.length > 0) {
    lines.push("  tag_source:");
    lines.push("    type: remap");
    lines.push(
      `    inputs: [${sourceKeys.map((k) => `"${k}"`).join(", ")}]`,
    );
    lines.push("    source: |-");
    lines.push(`      .logtura_connection_id = "${connection.id}"`);
    lines.push(`      .logtura_provider = "${driver.id}"`);
    lines.push("      .logtura_received_at = now()");
    lines.push("");
  }

  const upstreamForSinks =
    sourceKeys.length > 0 ? ["tag_source"] : [];

  // Per-monitor filter transforms.
  const monitorFilterKeys = new Map<string, string>();
  for (const m of monitors) {
    if (m.monitor.enabled !== 1) continue;
    if (upstreamForSinks.length === 0) continue;
    const key = `monitor_${safeKey(m.monitor.id)}_filter`;
    const condition = vrlConditionFor(
      m.monitor.filter_kind,
      m.monitor.filter_config_json,
    );
    lines.push(`  ${key}:`);
    lines.push("    type: filter");
    lines.push(
      `    inputs: [${upstreamForSinks.map((i) => `"${i}"`).join(", ")}]`,
    );
    lines.push("    condition: |-");
    for (const cl of condition.split("\n")) lines.push(`      ${cl}`);
    lines.push("");
    monitorFilterKeys.set(m.monitor.id, key);
  }

  // Per-sink optional refinement transforms + destination pre-sink
  // transforms.
  const sinkSinkKeys: Array<{ sinkKey: string; yaml: string }> = [];
  for (const m of monitors) {
    if (m.monitor.enabled !== 1) continue;
    const monitorFilterKey = monitorFilterKeys.get(m.monitor.id);
    if (!monitorFilterKey) continue;
    for (const sinkSpec of m.sinks) {
      const dDriver = getDestinationDriver(sinkSpec.destination.kind);
      if (!dDriver) continue;
      let upstream = monitorFilterKey;
      if (sinkSpec.sink.filter_kind) {
        const refKey = `sink_${safeKey(sinkSpec.sink.id)}_filter`;
        const refCondition = vrlConditionFor(
          sinkSpec.sink.filter_kind,
          sinkSpec.sink.filter_config_json,
        );
        lines.push(`  ${refKey}:`);
        lines.push("    type: filter");
        lines.push(`    inputs: ["${upstream}"]`);
        lines.push("    condition: |-");
        for (const cl of refCondition.split("\n"))
          lines.push(`      ${cl}`);
        lines.push("");
        upstream = refKey;
      }
      const sinkKey = `sink_${safeKey(sinkSpec.sink.id)}`;
      const envVarName = sinkEnvVarName(sinkSpec.sink.id);
      const bundle = dDriver.generateSinkBundle({
        config: sinkSpec.destinationConfig,
        inputs: [upstream],
        sinkKey,
        envVarName,
      });
      // Pre-sink transforms (Slack remap, etc.) live in `transforms:`.
      for (const t of bundle.preSinkTransforms ?? []) {
        lines.push(`  ${t.key}:`);
        lines.push(t.yaml);
        lines.push("");
      }
      // Stash the sink block for the sinks: section below.
      sinkSinkKeys.push({ sinkKey: bundle.sink.key, yaml: bundle.sink.yaml });
      // Collect runtime env var spec + value.
      const envSpec = dDriver.runtimeEnvVars({
        config: sinkSpec.destinationConfig,
        envVarName,
        displayName: sinkSpec.destination.display_name,
      });
      for (const e of envSpec) {
        sinkEnvVars.push({
          name: e.name,
          description: e.description,
          source: "destination",
          value: dDriver.envVarValue(sinkSpec.destinationConfig, e.name),
        });
      }
    }
  }

  // ---- sinks --------------------------------------------------------
  lines.push("sinks:");
  for (const ss of sinkSinkKeys) {
    lines.push(`  ${ss.sinkKey}:`);
    lines.push(ss.yaml);
    lines.push("");
  }
  if (sinkSinkKeys.length === 0 && sourceKeys.length > 0) {
    // No destinations configured yet — emit stdout so the pipeline
    // is still valid. The user gets unstructured output until they
    // wire up a destination.
    lines.push("  stdout:");
    lines.push("    type: console");
    lines.push('    inputs: ["tag_source"]');
    lines.push("    encoding:");
    lines.push("      codec: json");
    lines.push("");
  }
  lines.push("  prom_heartbeat:");
  lines.push("    type: prometheus_exporter");
  lines.push('    inputs: ["internal_metrics"]');
  lines.push('    address: "0.0.0.0:9598"');
  lines.push("");

  return { vectorYaml: lines.join("\n"), sinkEnvVars };
}

function vrlConditionFor(
  filterKind: string,
  filterConfigJson: string | null,
): string {
  const cfg = filterConfigJson
    ? (JSON.parse(filterConfigJson) as Record<string, unknown>)
    : {};
  if (filterKind === "all") return "true";
  if (filterKind === "level") {
    const lvl = String(cfg.level ?? "error");
    return `string(.level) == "${lvl.replace(/"/g, "")}"`;
  }
  if (filterKind === "pattern") {
    const pat = String(cfg.pattern ?? "");
    return `match(string!(.message ?? ""), r'${pat.replace(/'/g, "")}') ?? false`;
  }
  // Default and "errors": cheap, robust substring match on common
  // error words. Caught case-insensitively.
  const m =
    'msg = downcase(string!(.message ?? ""))\n' +
    'contains(msg, "error") || contains(msg, "exception") || ' +
    'contains(msg, "panic") || contains(msg, "fatal") || ' +
    'contains(msg, "critical")';
  return m;
}

function renderDockerfile(deps: DockerfileDep[]): string {
  const aptPackages = new Set<string>();
  for (const d of deps) {
    for (const p of d.aptPackages ?? []) aptPackages.add(p);
  }
  const aptList = [...aptPackages].sort().join(" ");
  const installSteps = deps.map((d) => `RUN ${d.install}`).join("\n");

  return `# Generated by logtura — https://logtura.dev
# Vector-based forwarder. Tails selected log sources and routes them
# through monitors to your configured destinations.

FROM timberio/vector:latest-debian

${aptList ? `RUN apt-get update && apt-get install -y --no-install-recommends ${aptList} && rm -rf /var/lib/apt/lists/*` : ""}
${installSteps}

COPY vector.yaml /etc/vector/vector.yaml

# Heartbeat (Prometheus exporter) — scrape from your monitoring stack.
EXPOSE 9598
# Vector API (vector top, debugging).
EXPOSE 8686

CMD ["vector", "--config", "/etc/vector/vector.yaml"]
`;
}

function renderRunCommand(envVars: BundleEnvVar[]): string {
  const flags = envVars.map((v) => {
    const placeholder =
      v.value !== null ? v.value : `<${v.name.toLowerCase()}>`;
    return `  -e ${v.name}="${placeholder}"`;
  });
  return [
    "docker build -t logtura-forwarder .",
    "",
    "docker run --rm \\",
    `${flags.join(" \\\n")} \\`,
    "  logtura-forwarder",
  ].join("\n");
}

// --- helpers ------------------------------------------------------

function safeKey(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, "_");
}

function sinkEnvVarName(sinkId: string): string {
  return `LOGTURA_SINK_${sinkId.replace(/[^a-zA-Z0-9]/g, "").toUpperCase()}_URL`;
}
