import type { ConnectionRow, LogSourceRow } from "./db";
import { getProvider } from "./providers";
import type {
  ConnectionRef,
  DockerfileDep,
  EnvVarSpec,
  ProviderDriver,
  SourceRef,
} from "./providers";

export interface GeneratedBundle {
  vectorYaml: string;
  dockerfile: string;
  runCommand: string;
  envVars: EnvVarSpec[];
  selectedCount: number;
}

interface GenerateInput {
  connection: ConnectionRow;
  selectedSources: LogSourceRow[];
}

export function generateBundle(input: GenerateInput): GeneratedBundle {
  const driver = getProvider(input.connection.provider);
  if (!driver) {
    throw new Error(`Unknown provider: ${input.connection.provider}`);
  }
  const connectionRef: ConnectionRef = {
    id: input.connection.id,
    externalAccountId: input.connection.external_account_id,
    displayName: input.connection.display_name,
  };
  const sourceRefs: SourceRef[] = input.selectedSources.map((s) => ({
    externalId: s.external_id,
    displayName: s.display_name,
    sourceKind: s.source_kind,
    metadata: s.metadata_json ? JSON.parse(s.metadata_json) : null,
  }));

  const spec = driver.runtimeSpec(connectionRef);
  const vectorYaml = renderVectorYaml(connectionRef, driver, sourceRefs);
  const dockerfile = renderDockerfile([spec.dockerfileDeps].flat());
  const runCommand = renderRunCommand(spec.envVars, input.connection);

  return {
    vectorYaml,
    dockerfile,
    runCommand,
    envVars: spec.envVars,
    selectedCount: sourceRefs.length,
  };
}

function renderVectorYaml(
  connection: ConnectionRef,
  driver: ProviderDriver,
  sources: SourceRef[],
): string {
  const lines: string[] = [];
  lines.push("# Generated by logtura — https://logtura.dev");
  lines.push(`# Connection: ${connection.displayName}`);
  lines.push(`# Provider: ${driver.id}`);
  lines.push(`# Account: ${connection.externalAccountId ?? "unknown"}`);
  lines.push("");
  lines.push("api:");
  lines.push("  enabled: true");
  lines.push('  address: "0.0.0.0:8686"');
  lines.push("");
  lines.push("sources:");

  const sourceKeys: string[] = [];

  if (sources.length === 0) {
    lines.push(
      "  # No sources selected — collector idles, only emitting heartbeat.",
    );
  } else {
    for (const s of sources) {
      const block = driver.generateSourceBlock({
        source: s,
        connection,
      });
      lines.push(`  ${block.key}:`);
      lines.push(block.yaml);
      sourceKeys.push(block.key);
    }
  }

  // Heartbeat — Vector's own internal metrics, scraped via the
  // prometheus_exporter sink. The control plane reads this to decide
  // whether the collector is alive.
  lines.push("  internal_metrics:");
  lines.push("    type: internal_metrics");
  lines.push("    scrape_interval_secs: 30");
  lines.push("");

  if (sourceKeys.length > 0) {
    lines.push("transforms:");
    lines.push("  tag_source:");
    lines.push("    type: remap");
    lines.push(
      `    inputs: [${sourceKeys.map((k) => `"${k}"`).join(", ")}]`,
    );
    lines.push("    source: |");
    lines.push(`      .logtura_connection_id = "${connection.id}"`);
    lines.push(`      .logtura_provider = "${driver.id}"`);
    lines.push("      .logtura_received_at = now()");
    lines.push("");
  }

  lines.push("sinks:");
  if (sourceKeys.length > 0) {
    lines.push("  stdout:");
    lines.push("    type: console");
    lines.push('    inputs: ["tag_source"]');
    lines.push("    encoding:");
    lines.push("      codec: json");
  }
  lines.push("  prom_heartbeat:");
  lines.push("    type: prometheus_exporter");
  lines.push('    inputs: ["internal_metrics"]');
  lines.push('    address: "0.0.0.0:9598"');
  lines.push("");

  return lines.join("\n");
}

function renderDockerfile(deps: DockerfileDep[]): string {
  const aptPackages = new Set<string>();
  for (const d of deps) {
    for (const p of d.aptPackages ?? []) aptPackages.add(p);
  }
  const aptList = [...aptPackages].sort().join(" ");
  const installSteps = deps.map((d) => `RUN ${d.install}`).join("\n");

  return `# Generated by logtura — https://logtura.dev
# Vector-based forwarder. Tails selected log sources and streams them
# (currently to stdout). Customize the sinks in vector.yaml to point
# at your destination of choice.

FROM timberio/vector:latest-debian

${aptList ? `RUN apt-get update && apt-get install -y --no-install-recommends ${aptList} && rm -rf /var/lib/apt/lists/*` : ""}
${installSteps}

COPY vector.yaml /etc/vector/vector.yaml

# Heartbeat (Prometheus exporter) — scrape from your monitoring stack.
EXPOSE 9598
# Vector API (vector top, debugging).
EXPOSE 8686

CMD ["vector", "--config", "/etc/vector/vector.yaml"]
`;
}

function renderRunCommand(
  envVars: EnvVarSpec[],
  connection: ConnectionRow,
): string {
  const flags = envVars.map((v) => {
    const placeholder =
      v.source === "external_account_id" && connection.external_account_id
        ? connection.external_account_id
        : `<${v.name.toLowerCase()}>`;
    return `  -e ${v.name}="${placeholder}"`;
  });
  return [
    "docker build -t logtura-forwarder .",
    "",
    "docker run --rm \\",
    `${flags.join(" \\\n")} \\`,
    "  logtura-forwarder",
  ].join("\n");
}
